// <auto-generated />
using Car_managment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Car_managment.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20200917135207_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Car_managment.Models.Car", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("IdTeam");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("IdCar");

                    b.HasIndex("IdTeam");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Car_managment.Models.Team", b =>
                {
                    b.Property<int>("IdTeam")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("IdTeam");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Car_managment.Models.Car", b =>
                {
                    b.HasOne("Car_managment.Models.Team", "Team")
                        .WithMany("cars")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
